# name: Run Automation Script

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main 

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2 

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.8'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run tests
#       run: |
#         pytest -s -v -n=3

name: Run Automation Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -s -v --html=Reports/report.html --self-contained-html

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: Reports/report.html  # Ensure this path matches the generated report location

    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots
        path: Reports/screenshots/  # Ensure this path matches where your screenshots are stored
